<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NEW HOMEWORK 3</title>
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous">
</head>
<body>
    <div>
       <img src="https://www.google.com/search?q=anh+thien+nhien+url&sxsrf=ALeKk01vUa944tKH_xoo7mk7Zb5siYNVig:1588698178364&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjY_s30mZ3pAhXslIsKHXqqDrYQ_AUoAXoECAwQAw&biw=2560&bih=888#imgrc=WKMMX_1mSY3hFM" width="100%" alt="">
       <p>"hellow"</p>
    </div>
</body>
</html>